[package]
name = "resfork-extract"
version = "0.1.0"
edition = "2018"
license = "MIT AND LGPL-2.1-or-later"
publish = false

[dependencies]
zip = { version = "2.2", default-features = false, features = ["deflate", "time"] }

[profile.release]
opt-level = 2
panic = "abort"
