pub fn decode_byte(byte: u8) -> char {
    match byte {
        0x00..=0x7F => char::from(byte),
        0x80 => '\u{00C4}', // LATIN CAPITAL LETTER A WITH DIAERESIS
        0x81 => '\u{00C5}', // LATIN CAPITAL LETTER A WITH RING ABOVE
        0x82 => '\u{00C7}', // LATIN CAPITAL LETTER C WITH CEDILLA
        0x83 => '\u{00C9}', // LATIN CAPITAL LETTER E WITH ACUTE
        0x84 => '\u{00D1}', // LATIN CAPITAL LETTER N WITH TILDE
        0x85 => '\u{00D6}', // LATIN CAPITAL LETTER O WITH DIAERESIS
        0x86 => '\u{00DC}', // LATIN CAPITAL LETTER U WITH DIAERESIS
        0x87 => '\u{00E1}', // LATIN SMALL LETTER A WITH ACUTE
        0x88 => '\u{00E0}', // LATIN SMALL LETTER A WITH GRAVE
        0x89 => '\u{00E2}', // LATIN SMALL LETTER A WITH CIRCUMFLEX
        0x8A => '\u{00E4}', // LATIN SMALL LETTER A WITH DIAERESIS
        0x8B => '\u{00E3}', // LATIN SMALL LETTER A WITH TILDE
        0x8C => '\u{00E5}', // LATIN SMALL LETTER A WITH RING ABOVE
        0x8D => '\u{00E7}', // LATIN SMALL LETTER C WITH CEDILLA
        0x8E => '\u{00E9}', // LATIN SMALL LETTER E WITH ACUTE
        0x8F => '\u{00E8}', // LATIN SMALL LETTER E WITH GRAVE
        0x90 => '\u{00EA}', // LATIN SMALL LETTER E WITH CIRCUMFLEX
        0x91 => '\u{00EB}', // LATIN SMALL LETTER E WITH DIAERESIS
        0x92 => '\u{00ED}', // LATIN SMALL LETTER I WITH ACUTE
        0x93 => '\u{00EC}', // LATIN SMALL LETTER I WITH GRAVE
        0x94 => '\u{00EE}', // LATIN SMALL LETTER I WITH CIRCUMFLEX
        0x95 => '\u{00EF}', // LATIN SMALL LETTER I WITH DIAERESIS
        0x96 => '\u{00F1}', // LATIN SMALL LETTER N WITH TILDE
        0x97 => '\u{00F3}', // LATIN SMALL LETTER O WITH ACUTE
        0x98 => '\u{00F2}', // LATIN SMALL LETTER O WITH GRAVE
        0x99 => '\u{00F4}', // LATIN SMALL LETTER O WITH CIRCUMFLEX
        0x9A => '\u{00F6}', // LATIN SMALL LETTER O WITH DIAERESIS
        0x9B => '\u{00F5}', // LATIN SMALL LETTER O WITH TILDE
        0x9C => '\u{00FA}', // LATIN SMALL LETTER U WITH ACUTE
        0x9D => '\u{00F9}', // LATIN SMALL LETTER U WITH GRAVE
        0x9E => '\u{00FB}', // LATIN SMALL LETTER U WITH CIRCUMFLEX
        0x9F => '\u{00FC}', // LATIN SMALL LETTER U WITH DIAERESIS
        0xA0 => '\u{2020}', // DAGGER
        0xA1 => '\u{00B0}', // DEGREE SIGN
        0xA2 => '\u{00A2}', // CENT SIGN
        0xA3 => '\u{00A3}', // POUND SIGN
        0xA4 => '\u{00A7}', // SECTION SIGN
        0xA5 => '\u{2022}', // BULLET
        0xA6 => '\u{00B6}', // PILCROW SIGN
        0xA7 => '\u{00DF}', // LATIN SMALL LETTER SHARP S
        0xA8 => '\u{00AE}', // REGISTERED SIGN
        0xA9 => '\u{00A9}', // COPYRIGHT SIGN
        0xAA => '\u{2122}', // TRADE MARK SIGN
        0xAB => '\u{00B4}', // ACUTE ACCENT
        0xAC => '\u{00A8}', // DIAERESIS
        0xAD => '\u{2260}', // NOT EQUAL TO
        0xAE => '\u{00C6}', // LATIN CAPITAL LETTER AE
        0xAF => '\u{00D8}', // LATIN CAPITAL LETTER O WITH STROKE
        0xB0 => '\u{221E}', // INFINITY
        0xB1 => '\u{00B1}', // PLUS-MINUS SIGN
        0xB2 => '\u{2264}', // LESS-THAN OR EQUAL TO
        0xB3 => '\u{2265}', // GREATER-THAN OR EQUAL TO
        0xB4 => '\u{00A5}', // YEN SIGN
        0xB5 => '\u{00B5}', // MICRO SIGN
        0xB6 => '\u{2202}', // PARTIAL DIFFERENTIAL
        0xB7 => '\u{2211}', // N-ARY SUMMATION
        0xB8 => '\u{220F}', // N-ARY PRODUCT
        0xB9 => '\u{03C0}', // GREEK SMALL LETTER PI
        0xBA => '\u{222B}', // INTEGRAL
        0xBB => '\u{00AA}', // FEMININE ORDINAL INDICATOR
        0xBC => '\u{00BA}', // MASCULINE ORDINAL INDICATOR
        0xBD => '\u{03A9}', // GREEK CAPITAL LETTER OMEGA
        0xBE => '\u{00E6}', // LATIN SMALL LETTER AE
        0xBF => '\u{00F8}', // LATIN SMALL LETTER O WITH STROKE
        0xC0 => '\u{00BF}', // INVERTED QUESTION MARK
        0xC1 => '\u{00A1}', // INVERTED EXCLAMATION MARK
        0xC2 => '\u{00AC}', // NOT SIGN
        0xC3 => '\u{221A}', // SQUARE ROOT
        0xC4 => '\u{0192}', // LATIN SMALL LETTER F WITH HOOK
        0xC5 => '\u{2248}', // ALMOST EQUAL TO
        0xC6 => '\u{2206}', // INCREMENT
        0xC7 => '\u{00AB}', // LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
        0xC8 => '\u{00BB}', // RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
        0xC9 => '\u{2026}', // HORIZONTAL ELLIPSIS
        0xCA => '\u{00A0}', // NO-BREAK SPACE
        0xCB => '\u{00C0}', // LATIN CAPITAL LETTER A WITH GRAVE
        0xCC => '\u{00C3}', // LATIN CAPITAL LETTER A WITH TILDE
        0xCD => '\u{00D5}', // LATIN CAPITAL LETTER O WITH TILDE
        0xCE => '\u{0152}', // LATIN CAPITAL LIGATURE OE
        0xCF => '\u{0153}', // LATIN SMALL LIGATURE OE
        0xD0 => '\u{2013}', // EN DASH
        0xD1 => '\u{2014}', // EM DASH
        0xD2 => '\u{201C}', // LEFT DOUBLE QUOTATION MARK
        0xD3 => '\u{201D}', // RIGHT DOUBLE QUOTATION MARK
        0xD4 => '\u{2018}', // LEFT SINGLE QUOTATION MARK
        0xD5 => '\u{2019}', // RIGHT SINGLE QUOTATION MARK
        0xD6 => '\u{00F7}', // DIVISION SIGN
        0xD7 => '\u{25CA}', // LOZENGE
        0xD8 => '\u{00FF}', // LATIN SMALL LETTER Y WITH DIAERESIS
        0xD9 => '\u{0178}', // LATIN CAPITAL LETTER Y WITH DIAERESIS
        0xDA => '\u{2044}', // FRACTION SLASH
        0xDB => '\u{20AC}', // EURO SIGN
        0xDC => '\u{2039}', // SINGLE LEFT-POINTING ANGLE QUOTATION MARK
        0xDD => '\u{203A}', // SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
        0xDE => '\u{FB01}', // LATIN SMALL LIGATURE FI
        0xDF => '\u{FB02}', // LATIN SMALL LIGATURE FL
        0xE0 => '\u{2021}', // DOUBLE DAGGER
        0xE1 => '\u{00B7}', // MIDDLE DOT
        0xE2 => '\u{201A}', // SINGLE LOW-9 QUOTATION MARK
        0xE3 => '\u{201E}', // DOUBLE LOW-9 QUOTATION MARK
        0xE4 => '\u{2030}', // PER MILLE SIGN
        0xE5 => '\u{00C2}', // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
        0xE6 => '\u{00CA}', // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
        0xE7 => '\u{00C1}', // LATIN CAPITAL LETTER A WITH ACUTE
        0xE8 => '\u{00CB}', // LATIN CAPITAL LETTER E WITH DIAERESIS
        0xE9 => '\u{00C8}', // LATIN CAPITAL LETTER E WITH GRAVE
        0xEA => '\u{00CD}', // LATIN CAPITAL LETTER I WITH ACUTE
        0xEB => '\u{00CE}', // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
        0xEC => '\u{00CF}', // LATIN CAPITAL LETTER I WITH DIAERESIS
        0xED => '\u{00CC}', // LATIN CAPITAL LETTER I WITH GRAVE
        0xEE => '\u{00D3}', // LATIN CAPITAL LETTER O WITH ACUTE
        0xEF => '\u{00D4}', // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
        0xF0 => '\u{F8FF}', // Apple logo
        0xF1 => '\u{00D2}', // LATIN CAPITAL LETTER O WITH GRAVE
        0xF2 => '\u{00DA}', // LATIN CAPITAL LETTER U WITH ACUTE
        0xF3 => '\u{00DB}', // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
        0xF4 => '\u{00D9}', // LATIN CAPITAL LETTER U WITH GRAVE
        0xF5 => '\u{0131}', // LATIN SMALL LETTER DOTLESS I
        0xF6 => '\u{02C6}', // MODIFIER LETTER CIRCUMFLEX ACCENT
        0xF7 => '\u{02DC}', // SMALL TILDE
        0xF8 => '\u{00AF}', // MACRON
        0xF9 => '\u{02D8}', // BREVE
        0xFA => '\u{02D9}', // DOT ABOVE
        0xFB => '\u{02DA}', // RING ABOVE
        0xFC => '\u{00B8}', // CEDILLA
        0xFD => '\u{02DD}', // DOUBLE ACUTE ACCENT
        0xFE => '\u{02DB}', // OGONEK
        0xFF => '\u{02C7}', // CARON
    }
}
